-- create tables

create table authors (
    id            number generated by default on null as identity
                  constraint authors_id_pk primary key,
    name          varchar2(150 char) not null,
    slug          varchar2(180 char) not null,
    email         varchar2(255 char),
    bio           clob,
    avatar_url    varchar2(500 char),
    active_yn     boolean,
    created       date not null,
    created_by    varchar2(255 char) not null,
    updated       date not null,
    updated_by    varchar2(255 char) not null
);



create table categories (
    id             number generated by default on null as identity
                   constraint categories_id_pk primary key,
    name           varchar2(150 char) not null,
    slug           varchar2(180 char) not null,
    description    varchar2(500 char),
    active_yn      boolean,
    created        date not null,
    created_by     varchar2(255 char) not null,
    updated        date not null,
    updated_by     varchar2(255 char) not null
);



create table posts (
    id                    number generated by default on null as identity
                          constraint posts_id_pk primary key,
    category_id           number                          constraint posts_category_id_fk
                          references categories,
    author_id             number                          constraint posts_author_id_fk
                          references authors,
    title                 varchar2(250 char) not null,
    slug                  varchar2(250 char) not null,
    excerpt               varchar2(500 char),
    content               clob,
    featured_image_url    varchar2(500 char),
    status                varchar2(20 char),
    published_at          timestamp,
    featured_yn           boolean,
    created               date not null,
    created_by            varchar2(255 char) not null,
    updated               date not null,
    updated_by            varchar2(255 char) not null
);

-- table index
create index posts_i1 on posts (category_id);

create index posts_i2 on posts (author_id);



create table tags (
    id            number generated by default on null as identity
                  constraint tags_id_pk primary key,
    name          varchar2(100 char) not null,
    slug          varchar2(120 char) not null,
    created       date not null,
    created_by    varchar2(255 char) not null,
    updated       date not null,
    updated_by    varchar2(255 char) not null
);



create table post_tags (
    id            number generated by default on null as identity
                  constraint post_tags_id_pk primary key,
    post_id       number                  constraint post_tags_post_id_fk
                  references posts,
    tag_id        number                  constraint post_tags_tag_id_fk
                  references tags,
    created       date not null,
    created_by    varchar2(255 char) not null,
    updated       date not null,
    updated_by    varchar2(255 char) not null
);

-- table index
create index post_tags_i1 on post_tags (post_id);

create index post_tags_i2 on post_tags (tag_id);



create table events (
    id             number generated by default on null as identity
                   constraint events_id_pk primary key,
    title          varchar2(250 char) not null,
    slug           varchar2(250 char) not null,
    description    clob,
    event_date     timestamp,
    location       varchar2(250 char),
    event_url      varchar2(500 char),
    status         varchar2(20 char),
    created        date not null,
    created_by     varchar2(255 char) not null,
    updated        date not null,
    updated_by     varchar2(255 char) not null
);



create table certifications (
    id                 number generated by default on null as identity
                       constraint certifications_id_pk primary key,
    name               varchar2(250 char) not null,
    issuer             varchar2(150 char),
    credential_id      varchar2(250 char),
    credential_url     varchar2(500 char),
    issued_date        date,
    expiration_date    date,
    description        clob,
    active_yn          boolean,
    created            date not null,
    created_by         varchar2(255 char) not null,
    updated            date not null,
    updated_by         varchar2(255 char) not null
);



-- triggers
create or replace trigger authors_biu
    before insert or update
    on authors
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end authors_biu;
/


create or replace trigger categories_biu
    before insert or update
    on categories
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end categories_biu;
/


create or replace trigger posts_biu
    before insert or update
    on posts
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end posts_biu;
/


create or replace trigger tags_biu
    before insert or update
    on tags
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end tags_biu;
/


create or replace trigger post_tags_biu
    before insert or update
    on post_tags
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end post_tags_biu;
/


create or replace trigger events_biu
    before insert or update
    on events
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end events_biu;
/


create or replace trigger certifications_biu
    before insert or update
    on certifications
    for each row
begin
    if inserting then
        :new.created := sysdate;
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.updated := sysdate;
    :new.updated_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end certifications_biu;
/


-- Generated by Quick SQL 1.2.9 8/13/2026, 11:15:51 AM

/*
authors
    name vc150 /nn
    slug vc180 /nn
    email vc255
    bio clob
    avatar_url vc500
    active_yn vc1 /values Y,N

categories
    name vc150 /nn
    slug vc180 /nn
    description vc500
    active_yn vc1 /values Y,N

posts
    category_id /fk categories
    author_id /fk authors
    title vc250 /nn
    slug vc250 /nn
    excerpt vc500
    content clob
    featured_image_url vc500
    status vc20 /values DRAFT,PUBLISHED,ARCHIVED
    published_at timestamp
    featured_yn vc1 /values Y,N

tags
    name vc100 /nn
    slug vc120 /nn

post_tags
    post_id /fk posts
    tag_id /fk tags

events
    title vc250 /nn
    slug vc250 /nn
    description clob
    event_date timestamp
    location vc250
    event_url vc500
    status vc20 /values UPCOMING,COMPLETED,CANCELLED

certifications
    name vc250 /nn
    issuer vc150
    credential_id vc250
    credential_url vc500
    issued_date date
    expiration_date date
    description clob
    active_yn vc1 /values Y,N




 Non-default options:
# settings = {"apex":"Y","auditcols":true,"db":"23","pk":"IDENTITY"}

*/